var gson = "2.13.2"

dependencies {
    compileOnly(
            'org.projectlombok:lombok:1.18.32',
            'org.jetbrains:annotations:23.1.0',
            "io.papermc.paper:paper-api:1.20.6-R0.1-SNAPSHOT",
    )
    annotationProcessor('org.projectlombok:lombok:1.18.32')

    implementation(
            project(':utils'),
            project(':versions:adapter'),

            project(':database'),

            project(':objects'),


            project(':config'),
            project(':bukkit-utils')
    )

    implementation(project(':commands')) {
        exclude group: "com.google.code.gson", module: "gson"
    }

    implementation(project(":versions:v1_20_r4"))
    implementation(project(":versions:v1_21_r1"))
    implementation(project(":versions:v1_21_r3"))
    implementation(project(":versions:v1_21_r5"))
    implementation(project(":versions:v1_21_r7"))

    compileOnly("com.google.code.gson:gson:${gson}")
}

processResources {
    filesMatching('**/plugin.yml') {
        expand(Map.of(
                "version", project.version,
                "gson", gson
        ))
    }
}

tasks {
    shadowJar {
        archiveFileName = 'WLib-' + project.version + '.jar'
        relocate("com.github.sisyphsu", "com.wizardlybump17.wlib.libs.com.github.sisyphsu")
    }
}

