var gson = "2.13.2"
var manifold = "2025.1.27"

apply plugin: "systems.manifold.manifold-gradle-plugin"

dependencies {
    compileOnly(
            'org.projectlombok:lombok:1.18.32',
            'org.jetbrains:annotations:23.1.0',
            "io.papermc.paper:paper-api:1.20.6-R0.1-SNAPSHOT",
    )
    annotationProcessor('org.projectlombok:lombok:1.18.32')

    implementation(
            project(':utils'),
            project(':versions:adapter'),

            project(':database'),

            project(':objects'),


            project(':config'),
            project(':bukkit-utils')
    )

    implementation(project(':commands')) {
        exclude group: "com.google.code.gson", module: "gson"
    }

    if (!"true".equals(rootProject.properties.get("skip_nms"))) {
        implementation(project(":versions:v1_20_R4"))
        implementation(project(":versions:v1_21_R1"))
        implementation(project(":versions:v1_21_R3"))
        implementation(project(":versions:v1_21_R5"))
    } else {
        println("Ignoring NMS")
    }

    compileOnly("com.google.code.gson:gson:${gson}")

    annotationProcessor("systems.manifold:manifold-preprocessor:${manifold}")
    testAnnotationProcessor("systems.manifold:manifold-preprocessor:${manifold}")
}

processResources {
    filesMatching('**/plugin.yml') {
        expand(Map.of(
                "version", project.version,
                "gson", gson
        ))
    }
}

tasks {
    shadowJar {
        archiveFileName = 'WLib-' + project.version + '.jar'
        relocate("com.github.sisyphsu", "com.wizardlybump17.wlib.libs.com.github.sisyphsu")
    }
}

def preprocessors() {
    StringBuilder preprocessors = new StringBuilder()

    if ("true".equals(rootProject.properties.get("skip_nms"))) {
        preprocessors.append("WLIB_INCLUDE_NMS=0")
    } else {
        preprocessors.append("WLIB_INCLUDE_NMS=1")
    }

    println("Preprocessors: ${preprocessors}")

    new File(rootProject.projectDir, "build.properties").text = preprocessors.toString()
}

preprocessors()
