name: WLib
main: com.wizardlybump17.wlib.WLib
version: '${version}'
author: WizardlyBump17
api-version: '1.13'
load: STARTUP
libraries:
  - net.kyori:adventure-api:4.18.0
  - net.kyori:adventure-text-minimessage:4.18.0
  - net.kyori:adventure-platform-bukkit:4.3.4
