name: Build and upload

on:
  push:
  pull_request:
    types:
      - opened
      - reopened

env:
  USERNAME: ${{ github.actor }}
  TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Get current date
        run: echo "WLIB_BUILD_DATE=$(date +'%Y-%m-%d_%H-%M-%S')" >> "$GITHUB_ENV"
      - uses: actions/checkout@v4
      - name: Run BuildTools
        uses: ./.github/actions/buildtools/setup-and-run
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build
        run: ./gradlew build
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          path: "**/build/libs/*.jar"
          name: WLib-${{ env.WLIB_BUILD_DATE }}
          if-no-files-found: error