name: Publish to GitHub Packages

on:
  push:
  pull_request:
    types:
      - opened
      - reopened

env:
  USERNAME: ${{ github.actor }}
  TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Run BuildTools
        uses: ./.github/actions/buildtools/setup-and-run
      - name: Set up JDK 16
        uses: actions/setup-java@v4
        with:
          java-version: 16
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build
        run: ./gradlew build
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          path: |
            **/build/libs
            !/build/libs
          name: WLib
          if-no-files-found: error