name: Publish to GitHub Packages

on:
  push:
  pull_request:
    types:
      - opened
      - reopened

env:
  USERNAME: ${{ github.actor }}
  TOKEN: ${{ secrets.GITHUB_TOKEN }}
  WLIB_UPLOAD_FILES: |
    bukkit-utils/build/libs/*.jar
    bungee/build/libs/*.jar
    commands/build/libs/*.jar
    config/build/libs/*.jar
    core/build/libs/*.jar
    database/build/libs/*.jar
    objects/build/libs/*.jar
    utils/build/libs/*.jar
    versions/adapter/build/libs/*.jar
    versions/v1_20_R4/build/libs/*.jar
    versions/v1_21_R1/build/libs/*.jar
    versions/v1_21_R3/build/libs/*.jar

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Run BuildTools
        uses: ./.github/actions/buildtools/setup-and-run
      - name: Set up JDK 16
        uses: actions/setup-java@v4
        with:
          java-version: 16
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build
        run: ./gradlew build
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          path: ${{ env.WLIB_UPLOAD_FILES }}
          name: WLib