name: Build

on:
  push:
  pull_request:

env:
  USERNAME: ${{ secrets.GITHUB_TOKEN }}
  TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Run BuildTools
        uses: ./.github/actions/buildtools/setup-and-run
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582
      - name: Build with Gradle Wrapper
        run: ./gradlew build
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          path: "**/build/libs/*"