name: Publish to GitHub Packages

on:
  release:
    types:
      - created
      - published
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Run BuildTools
        uses: ./.github/workflows/buildtools/setup-and-run
      - name: Set up JDK 16
        uses: actions/setup-java@v4
        with:
          java-version: 16
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582
      - name: Build with Gradle Wrapper
        run: ./gradlew publish
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
